@startuml Hexagonal Architecture Workflow

autonumber "<b>[00]"

actor Client
box
participant InputAdapter
participant ApplicationLayer
participant DomainLayer
participant OutputAdapter
end box
participant Service

Client -> InputAdapter : request
activate InputAdapter

InputAdapter -> ApplicationLayer : C/Q transaction
activate ApplicationLayer

ApplicationLayer -> DomainLayer : business logic
activate DomainLayer
DomainLayer --> ApplicationLayer : return
deactivate DomainLayer

ApplicationLayer -> OutputAdapter : write changes
activate OutputAdapter

OutputAdapter <--> Service : invoke

OutputAdapter --> ApplicationLayer : return
deactivate OutputAdapter

ApplicationLayer --> InputAdapter : end transaction
deactivate ApplicationLayer

InputAdapter --> Client : response
deactivate InputAdapter

@enduml